services:
  - type: web
    name: impostor-futbolero
    runtime: node
    region: oregon
    plan: free
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOSTNAME
        value: 0.0.0.0
